module.exports = {
    MongoIDPattern : /^(?=[a-f\d]{24}$)(\d+[a-f]|[a-f]+\d)/i ,
    //when you freeze a object, then you can change the property value of that object or can not add
    //new property to it
    ROLES : Object.freeze({
        //ordinary users
        USER : "USER",
        //admin of site
        ADMIN : "ADMIN",
        //super admin of site
        SUPERADMIN : "SUPERADMIN",
        // persons who just produce cotext(add products or write blogs)
        WRITER : "WRITER",
        //person who is the owner of a virtual product
        TEACHER : "TEACHER",
        // person who is the owner of a product
        SUPPLIER : "SUPPLIER",
         // person who is the front-end developer of the website
        DEVELOPER : "DEVELOPER",
    }),
    PERMISSIONS : Object.freeze({
        USER : [
        "get otp",
        "check otp",
        "refresh token",
        "get user profile",
        "update user profile",
        "get one course",
        "get course list",
        "get chapter list",
        "get product list",
        "get one product",
        "get blog list",
        "get one blog",
        "get list of parent categories",
        "get children of a category",
        "get  category list",
        "get one category"
    ],
        ADMIN : [    
  "get otp",
  "check otp",
  "refresh token",
  "get user profile",
  "update user profile",
  "get one course",
  "get course list",
  "get chapter list",
  "get product list",
  "get one product",
  "get blog list",
  "get one blog",
  "get list of parent categories",
  "get children of a category",
  "get  category list",
  "get one category",
  "get user list",
  "add one course",
  "update one course",
  "add one chapter",
  "remove one chapter",
  "update one chapter",
  "add one episode",
  "remove one episode",
  "update one episode",
  "add one product",
  "remove one product",
  "update one product",
  "delete one product image",
  "add one product image",
  "add one blog",
  "update one blog",
  "delete one blog",
  "add one category",
  "delete one category",
  "update one category",
  "hash password",
  "random number"
        ],
        SUPERADMIN : [
            "get otp",
  "check otp",
  "refresh token",
  "get user profile",
  "update user profile",
  "get one course",
  "get course list",
  "get chapter list",
  "get product list",
  "get one product",
  "get blog list",
  "get one blog",
  "get list of parent categories",
  "get children of a category",
  "get  category list",
  "get one category",
  "get user list",
  "add one course",
  "update one course",
  "add one chapter",
  "remove one chapter",
  "update one chapter",
  "add one episode",
  "remove one episode",
  "update one episode",
  "add one product",
  "remove one product",
  "update one product",
  "delete one product image",
  "add one product image",
  "add one blog",
  "update one blog",
  "delete one blog",
  "add one category",
  "delete one category",
  "update one category",
  "hash password",
  "random number"
        ],
        WRITER :[
            "get otp",
  "check otp",
  "refresh token",
  "get user profile",
  "update user profile",
  "get one course",
  "get course list",
  "get chapter list",
  "get product list",
  "get one product",
  "get blog list",
  "get one blog",
  "get list of parent categories",
  "get children of a category",
  "get  category list",
  "get one category",
  "add one blog",
  "update one blog",
  "add one category",
        ],
        TEACHER :[
            "get otp",
  "check otp",
  "refresh token",
  "get user profile",
  "update user profile",
  "get one course",
  "get course list",
  "get chapter list",
  "get product list",
  "get one product",
  "get blog list",
  "get one blog",
  "get list of parent categories",
  "get children of a category",
  "get  category list",
  "get one category",
  "add one course",
  "update one course",
  "add one chapter",
  "remove one chapter",
  "update one chapter",
  "add one episode",
  "remove one episode",
  "update one episode"
        ],
        SUPPLIER : [
            "get otp",
  "check otp",
  "refresh token",
  "get user profile",
  "update user profile",
  "get one course",
  "get course list",
  "get chapter list",
  "get product list",
  "get one product",
  "get blog list",
  "get one blog",
  "get list of parent categories",
  "get children of a category",
  "get  category list",
  "get one category",
  "add one product",
  "update one product",
  "delete one product image",
  "add one product image"
        ],
        DEVELOPER:[
            "get otp",
  "check otp",
  "refresh token",
  "get user profile",
  "update user profile",
  "get one course",
  "get course list",
  "get chapter list",
  "get product list",
  "get one product",
  "get blog list",
  "get one blog",
  "get list of parent categories",
  "get children of a category",
  "get  category list",
  "get one category",
  "hash password",
  "random number"
        ],
        ALL : "all"
    }),
    ACCESS_TOKEN_SECRET_KEY : "CCEBD888251E547C877C43A324B5DE12468F431EA0D19A259751E2C80EE35876",
    REFRESH_TOKEN_SECRET_KEY : "782285F688AC9B7CFF599230A39C49558A9D4B615B85AF706A80FAF52C897FB5",
    COOKIE_PARSER_SECRET_KEY : "F5B9A2C123ED6C11FFCC82D331681E25372112B817F76B28114993B57CAB3BC8"
}